# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
	minecraft_version=26.1
	loader_version=0.18.5
    loom_version=1.15-SNAPSHOT

# Mod Properties
	mod_version = 2.3.0
	maven_group = org.lolicode
	archives_base_name = NekoMusic_Client-fabric-26.1

# Dependencies
	# check this on https://modmuss50.me/fabric.html
	fabric_version=0.144.3+26.1
	cloth_config_version=26.1.154
	modmenu_version=18.0.0-alpha.8
	badpackets_version=0.12.1
	fabric_language_kotlin_version=1.13.10+kotlin.2.3.20
	plasmovoice_version = 2.1.8

	# non-mod dependencies
	okhttp_version=4.12.0
	okio_version=3.16.0
	jlayer_version=1.0.3
	tika_version=3.2.3
	commons_text_version=1.15.0
