// AI usage notice: This file is generated by GPT-codex-5.3

package org.lolicode.nekomusiccli.mixin;

import net.minecraft.sounds.SoundSource;
import org.lolicode.nekomusiccli.config.CustomSoundCategory;
import org.objectweb.asm.Opcodes;
import org.spongepowered.asm.mixin.Final;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Mutable;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.gen.Invoker;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Locale;

@Mixin(SoundSource.class)
public abstract class SoundSourceMixin {
    @SuppressWarnings("ShadowTarget")
    @Shadow
    @Final
    @Mutable
    private static SoundSource[] $VALUES;

    @SuppressWarnings("InvokerTarget")
    @Invoker("<init>")
    private static SoundSource nekomusiccli$newSoundSource(String internalName, int ordinal, String name) {
        throw new AssertionError();
    }

    @Unique
    private static final String NEKOMUSICCLI_CATEGORY_ID = "nekomusiccli$nekomusic";

    @Inject(
            method = "<clinit>",
            at = @At(
                    value = "FIELD",
                    target = "Lnet/minecraft/sounds/SoundSource;$VALUES:[Lnet/minecraft/sounds/SoundSource;",
                    opcode = Opcodes.PUTSTATIC,
                    shift = At.Shift.AFTER,
                    remap = false
            )
    )
    private static void nekomusiccli$appendCategory(CallbackInfo ci) {
        var categories = new ArrayList<>(Arrays.asList($VALUES));
        var category = nekomusiccli$newSoundSource(
                "NEKOMUSICCLI_NEKOMUSIC",
                categories.getLast().ordinal() + 1,
                NEKOMUSICCLI_CATEGORY_ID.toLowerCase(Locale.ROOT)
        );
        categories.add(category);
        $VALUES = categories.toArray(SoundSource[]::new);
        CustomSoundCategory.NEKOMUSIC = category;
    }
}
