# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        description: Publish a Release
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: setup jdk 21
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b
        with:
          dependency-graph: generate-and-submit
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: Artifacts
          path: build/libs/

      - name: Get version from gradle.properties
        id: get_version
        run: |
          version=$(grep "^\W*mod_version" gradle.properties | cut -d'=' -f2 | xargs)
          echo "version=$version" >> $GITHUB_ENV

      - name: Check commit author and verification
        id: check_commit
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          COMMIT_DETAILS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/commits/$COMMIT_SHA)
          COMMIT_AUTHOR=$(echo $COMMIT_DETAILS | jq -r '.commit.author.name')
          VERIFIED=$(echo $COMMIT_DETAILS | jq -r '.commit.verification.verified')
          echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_ENV
          echo "VERIFIED=$VERIFIED" >> $GITHUB_ENV

      - name: Publish Release
        if: ${{ github.event_name != 'pull_request' && (github.event.inputs.release == 'true' || (env.COMMIT_AUTHOR == 'KoishiMoe' && env.VERIFIED == 'true' && contains(github.event.head_commit.message, '[release]'))) }}
        uses: Kir-Antipov/mc-publish@995edadc13559a8b28d0b7e6571229f067ec7659
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: myfmwwbW
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # Only include this section if you wish to publish
          # your assets on GitHub.
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: "v${{ env.version }}-neo-1.21.10"
          name: "Release v${{ env.version }} for neoforge 1.21.10"
